### ISSUE TITLE
S3 GetMetadataAsync get null metadata although the metadata is written to s3 object.

### ISSUE THREAD

**Issue by Lewis-Teoh** [bechtleav360/tusdotnet.Storage.S3#1]
Hi, I observed that is an issue when trying to GetMetadataAsync from the file, it returns nothing, the root cause is this function when joining the string of metadata collection returns from s3.

![image](https://github.com/bechtleav360/tusdotnet.Storage.S3/assets/33535303/2871f822-9834-442e-a709-b45e0703b941)
There's a spacing after the comma which caused the MetadataParser unable to parse the metadata.
This is the following constructed metadata string:
`x-amz-meta-filename a2V5Y2xvYWstMjMuMC42LnppcA==, x-amz-meta-filetype YXBwbGljYXRpb24veC16aXAtY29tcHJlc3NlZA==, x-amz-meta-relativepath bnVsbA==`

Error message that thrown by MetadataParser.
`Header Upload-Metadata: The Upload-Metadata request and response header MUST consist of one or more comma - separated key - value pairs. The key and value MUST be separated by a space.The key MUST NOT contain spaces and commas and MUST NOT be empty. The key SHOULD be ASCII encoded and the value MUST be Base64 encoded. All keys MUST be unique. The value MAY be empty. In these cases, the space, which would normally separate the key and the value, MAY be left out.`

While I checked and compared with the original local disk metadata string, it looks like this and no problem of parsing it.
`relativePath bnVsbA==,name a2V5Y2xvYWstMjMuMC42LnppcA==,type YXBwbGljYXRpb24veC16aXAtY29tcHJlc3NlZA==,filetype YXBwbGljYXRpb24veC16aXAtY29tcHJlc3NlZA==,filename a2V5Y2xvYWstMjMuMC42LnppcA==`

**Comment by teian** [comment]
Thanks for the report. I will look into this

**Comment by teian** [comment]
There is another issue I need to address. the x-amz-meta- prefix should be removed.

**Comment by Lewis-Teoh** [comment]
Yup, I think you can remove from this function as well by string replace method.

**Comment by teian** [comment]
Sure but it does not retain the case of the keys. Seems to be sdk related. Maybe I simply move this to the info object.
